### ISSUE TITLE
Question: is it possible to use this for showing a video, too?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [kloverde/android-LibGdxLiveWallpaperTemplate#1]
I've noticed this sample too, of showing a video using LibGdx:
https://github.com/libgdx/gdx-video

It doesn't seem to "fit" what's shown there, meaning that here it has a function of "render" that needs to be called all the time.
Yet there it's quite automatic, as it binds to the MediaPlayer, and seem to use a different function, of "update" instead, probably to prepare the next frame.

Is there really a way to use LibGdx to show a video on a live wallpaper?
Could I also make it translate (move) horizontally, as you scroll (using `offsetChange`), and scale it accordingly to have something like scale-crop of images on Android?

**Comment by kloverde** [comment]
> Is there really a way to use LibGdx to show a video on a live wallpaper?

I'm sorry, I don't know - I've never worked with video in libgdx.  This repository is only slightly less than the entirety of my libgdx experience (that is to say, not much).

> here it has a function of "render" that needs to be called all the time.  Yet there it's quite automatic [...]

The libgdx `VideoPlayer` class is the finished product that decides what a frame looks like and takes care of drawing it.

With the wallpaper, you're the one deciding what a frame looks like.  Your implementation of a wallpaper service is the finished product, analagous to `VideoPlayer`.

With the wallpaper example, you'd have a separate thread calculating positions of objects (for example, a ball) based on elapsed time, and `render` would access those values to draw the objects at the calculated position.

> Could I also make it translate (move) horizontally, as you scroll (using offsetChange), and scale it accordingly to have something like scale-crop of images on Android?

I can't answer these questions with respect to video, since I haven't worked with it before.  One piece of useful information I can give you is about `offsetChange`:  it's awful, but its awfulness has nothing to do with libgdx.  Here comes a lot of information - maybe you already know this, maybe not:

`OffsetChange` is a libgdx alias for `WallpaperService.Engine.onOffsetsChanged`.  This method is called by the launcher in response to the user moving their finger across the screen.  The launcher is responsible for determining how much the wallpaper should be translated in response to the user action.  It's supposed to pass these precalculated values to you, and you're supposed to just receive them and use them without needing to figure anything out.

God only knows why Google decided to make the launcher responsible for managing this instead of the Android system.  This decision to make every launcher developer reinvent the wheel has resulted in many broken wallpapers.  Many launchers either don't implement `onOffsetsChanged` at all, or their implementations are broken.  The result is wallpapers that either don't scroll at all, or behave incorrectly.

Samsung, for example, doesn't implement it at all.  [This was a deliberate decision by Samsung](http://web.archive.org/web/20140417231223/http://developer.samsung.com/forum/thread/onoffsetschanged-not-called-in-live-wallpaper/77/217103?boardName=GeneralB&startId=zzzzz~#post5).  They have a sizable market share, and your wallpaper just flat-out won't scroll on their devices if you rely on `onOffsetsChanged`/`offsetChange`.

If you want your wallpaper to scroll on all devices, you need to roll your own solution.  In the world of libgdx, you can use `GestureDetector.GestureListener` to listen to input events.  The methods you'll be interested in are `pan` and `fling`.  Use `pan` to drag the wallpaper around while a finger is in contact with the screen.  Use `fling` to keep the wallpaper moving after the user lifts their finger.  You can use built-in easing functions provided by libgdx to bring the scrolling to a gradual stop.  I've found that `com.badlogic.gdx.math.Interpolation.pow4Out` works best, in my opinion.

Since libgdx is sitting between us and WallpaperService, they could have handled this for us and given us an implementation that works across the board, but they didn't (not that they have an obligation to).

I have this alternative scrolling implementation turned on by default in my own wallpaper (personal project, not this repository).  I let the user disable it in the Settings screen (along with a warning that it might cause scrolling to stop working).

All that having been said, I don't know why you'd want to scroll a video, but you know your use case better than me.  :)

**Comment by AndroidDeveloperLB** [comment]
@kloverde Yes thanks.
I've actually already have a live-wallpaper app ([here](https://play.google.com/store/apps/details?id=com.lb.lwp_plus)). I use the normal API though, without any graphics engine. I created it originally to have dark-colors on the OS for Android 8.1, and later for supporting colors of Material You.

I was thinking that maybe I should give it a try, because I wanted to provide a way to show videos, and not just images/animations. LibGdx can handle both images and videos already, so it should be possible.
In the past I also noticed about the horizontal scrolling. Didn't know it was intentional. How weird. 

Would you please create a new sample based on your personal project on Github, that show how to view videos using LibGdx, with scrolling? If you wish, I can donate you a bit to encourage it, or put credits to you on the app.


As for scrolling a video, that's because the input video doesn't always match 100% to the screen. Sometimes the video is horizontal, yet the current orientation is vertical. And the opposite.

**Comment by kloverde** [comment]
> Would you please create a new sample based on your personal project on Github, that show how to view videos using LibGdx, with scrolling?

Sorry, that's not something I'm interested in learning.  I recommend asking the libgdx community: https://libgdx.com/community/discord/
